### ISSUE TITLE
 apache_get_modules()

### ISSUE THREAD

**Issue by glombers** [addictivehub/addictive-community#113]
Using niginx Fatal error: Call to undefined function apache_get_modules() in /var/www/html/forum/install/index.php on line 175

mod_rewrite:
`location / {
        root   /var/www/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.php?$args;
    }`

**Comment by brunnopleffken** [comment]
For now Nginx is not supported, only Apache servers (although I want to expand to Nginx and IIS in the near future).

If you'd like to work on mod_rewrite for Nginx, a Pull Request will be welcome! This is the only case where a specific PHP function is used for Apache (`apache_get_modules`).

**Comment by glombers** [comment]
As for me, I should be support for apache nginx light etc. we will do it ? what do you say

**Comment by R-J** [comment]
Instead of simply showing an error I would advice to show a notice that your forum requires Apache as long as there is no official nginx config available.

As mentioned in [my issue](https://github.com/brunnopleffken/addictive-community/issues/120), there is another usage of an Apache specific "function": the server variable REDIRECT_URL is filled by Apache only.
